// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/da/messages.json"
    | "/_locales/de/messages.json"
    | "/_locales/en/messages.json"
    | "/_locales/es/messages.json"
    | "/_locales/fa/messages.json"
    | "/_locales/fr/messages.json"
    | "/_locales/it/messages.json"
    | "/_locales/ja/messages.json"
    | "/_locales/ml/messages.json"
    | "/_locales/no/messages.json"
    | "/_locales/ru/messages.json"
    | "/_locales/sv/messages.json"
    | "/_locales/zh_CN/messages.json"
    | "/_locales/zh_TW/messages.json"
    | "/background.js"
    | "/content-scripts/hf-pull.js"
    | "/content-scripts/ollama-pull.js"
    | "/content-scripts/youtube-summarize.js"
    | "/icon.png"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/64.png"
    | "/ocr/lang/eng-fast.traineddata.gz"
    | "/ocr/tesseract-core-simd.js"
    | "/ocr/tesseract-core-simd.wasm"
    | "/ocr/worker.min.js"
    | "/options.html"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
